#ifndef SETTINGS_HPP
#define SETTINGS_HPP

#define DEFAULT_SCREEN_WIDTH 800
#define DEFAULT_SCREEN_HEIGHT 600
#define DEFAULT_SCREEN_TITLE "Engine v0.0.1"

#define DEFAULT_FPS 60.0F
#define DEFAULT_DELTATIME 1.5F

#define DEFAULT_SPEED_X 10.0F
#define DEFAULT_SPEED_Y 10.0F

#define DEFAULT_FPS_SIMULATION 60.0f

#define BACKWARD_DIRECTION -1.0
#define FORWARD_DIRECTION 1.0
#define UPWARD_DIRECTION -1.0
#define DOWNWARD_DIRECTION 1.0

#endif
